apiVersion: skaffold/v2beta21
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/kubernetes/*
build:
  local:
    push: false
  artifacts:
    - image: tanweerhossain/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .