name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dummy Continuous Deployment
        run: echo -e "1. Create an account in a Kubernetes Cluster Hosting Service Provider i.e Digital Ocean\n2. Uncomment the following command"
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - name: Save ticketing cluster's credentials to your local kubeconfig
      #   run: doctl kubernetes cluster kubeconfig save ticketing
      # - name: Pulling the updated container image and restarting the deployment service
      #   run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
