name: tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Test Auth Microservice
        run: cd auth && npm install && npm run test:ci
      - name: Test Ticket Microservice
        run: cd ../tickets && npm install && npm run test:ci
      - name: Test Order Microservice
        run: cd ../orders && npm install && npm run test:ci
      - name: Test Expiration Microservice
        run: cd ../expiration && npm install && npm run test:ci
      - name: Test Payment Microservice
        run: cd ../payments && npm install && npm run test:ci
