name: tests-orders
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Test Order Microservice
        run: cd orders && npm install && npm run test:ci
