name: tests-auth
on: pull_request:
  paths:
    - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Test Auth Microservice
        run: cd auth && npm install && npm run test:ci
