name: tests-payments
on: pull_request:
  paths:
    - 'payments/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Test Payment Microservice
        run: cd payments && npm install && npm run test:ci
